# my aliases
alias nv='nvim'
alias v='vim'
alias ff='fastfetch'
alias ls='exa'
alias lg='lazygit'
alias mk='make'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cm='chezmoi'
alias up='sudo pacman -Syu'
alias ra='yazi'
alias py='python3'
alias pip='pip3'
alias z='zathura'
alias pingo='ping google.com'
alias ccf='codecrafters'
