# [Volume]
# command=bash ~/.config/i3/scripts/volume.sh
# interval=1

[Simple]
full_text= | 
color=#717171

[Memory]
command=bash ~/.config/i3/scripts/memory.sh

[Simple]
full_text= | 
color=#717171

[Battery]
command=bash ~/.config/i3/scripts/battery.sh

interval=30

[Simple]
full_text= | 
color=#717171

[Date]
label=<span color='#89b4fa'> </span>
markup=pango
command=date +'%A %h %d,%Y'
interval=once

[Simple]
full_text= | 
color=#717171

[Time]
label=<span color='#89b4fa'>󱑁 </span>
markup=pango
command=date +'%I:%M %p'
interval=1


